# Generated by Django 6.0.2 on 2026-04-17 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('DUE', 'Due'), ('ABOUT_TO_DUE', 'About to be Due'), ('OVERDUE', 'Overdue'), ('RESOLVED', 'Resolved')], default='DUE', max_length=50),
        ),
        migrations.AddField(
            model_name='animal',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('VACCINE_DUE', 'Vaccination Due'), ('TREATMENT_DUE', 'Treatment Due'), ('VET_VISIT', 'Veterinary Visit'), ('GEOFENCE_BREACH', 'Geo-fence Breach'), ('HEALTH_RISK', 'Health Risk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='current_paddock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.paddock'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='qr_code',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='boundary_radius_m',
            field=models.FloatField(help_text='Geo-fence radius in metres. Set ≥ 100 m for reliable boundaries.'),
        ),
        migrations.AlterField(
            model_name='paddock',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paddocks', to='app.farm'),
        ),
    ]
